# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  PHP: true
exclude_paths:
 - "application/third_party/*"
 - "application/tests/*"
 - "public/assets/js/jquery*"
 - "public/assets/js/bootstrap*"
 - "public/assets/css/bootstrap*"